### ISSUE TITLE
Error when starting / decamelize/index.js:9 SyntaxError: Invalid regular expression: / Invalid escape 

### ISSUE THREAD

**Issue by Eisteed** [Tucsky/aggr-server#6]
Hi, Thank you for sharing such a good project source,
I'm trying to run aggr-server to access data locally, I'm using a fresh ubuntu server 18.04 LTS
Installed nodejs and npm, no issues when running npm build but when I try to run node index I'm getting this error :
```
using config file config.json
/home/test/aggr-server/node_modules/decamelize/index.js:9
                .replace(/([\p{Lowercase_Letter}\d])(\p{Uppercase_Letter})/gu, `$1${separator}$2`)
                 ^

SyntaxError: Invalid regular expression: /([\p{Lowercase_Letter}\d])(\p{Uppercase_Letter})/: Invalid escape
    at module.exports (/home/test/aggr-server/node_modules/decamelize/index.js:9:4)
    at Object.keys.forEach (/home/test/aggr-server/src/config.js:244:23)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/test/aggr-server/src/config.js:243:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

I can't find much help about this error on the google so if you know what I'm doing wrong thanks in advance. 👍

**Comment by Tucsky** [comment]
What command did you run exactly? And what version of node are you using?
